"""added first migration 5

Revision ID: 0fa9ed3f3039
Revises: 37c666816a3c
Create Date: 2024-07-07 22:21:31.369382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fa9ed3f3039'
down_revision = '37c666816a3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chatbot_instruction_categories', schema=None) as batch_op:
        batch_op.drop_column('bot9_instruction_category_icon')
        batch_op.drop_column('bot9_instruction_category_slug')

    with op.batch_alter_table('chatbot_instructions', schema=None) as batch_op:
        batch_op.drop_column('position')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chatbot_instructions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('chatbot_instruction_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bot9_instruction_category_slug', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('bot9_instruction_category_icon', sa.VARCHAR(length=256), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
