"""added first migration

Revision ID: 4099b0017225
Revises: 
Create Date: 2024-07-07 21:41:15.784418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4099b0017225'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('chatbots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bot9_chatbot_id', sa.UUID(), nullable=True),
    sa.Column('bot9_chatbot_name', sa.String(length=256), nullable=True),
    sa.Column('bot9_chatbot_url', sa.String(length=256), nullable=True),
    sa.Column('bot9_state', sa.String(length=256), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chatbots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chatbots_bot9_chatbot_id'), ['bot9_chatbot_id'], unique=True)

    op.create_table('tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bot9_token', sa.String(length=1000), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tokens_bot9_token'), ['bot9_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('chatbot_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bot9_chatbot_id', sa.UUID(), nullable=False),
    sa.Column('bot9_action_id', sa.UUID(), nullable=True),
    sa.Column('bot9_action_name', sa.String(length=256), nullable=True),
    sa.Column('bot9_action_description', sa.Text(), nullable=True),
    sa.Column('bot9_action_type', sa.String(length=64), nullable=True),
    sa.Column('bot9_action_meta', sa.Text(), nullable=True),
    sa.Column('is_active_on_bot9', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bot9_chatbot_id'], ['chatbots.bot9_chatbot_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bot9_action_id')
    )
    op.create_table('chatbot_instruction_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bot9_chatbot_id', sa.UUID(), nullable=False),
    sa.Column('bot9_instruction_category_id', sa.UUID(), nullable=False),
    sa.Column('bot9_instruction_category_name', sa.String(length=256), nullable=False),
    sa.Column('bot9_instruction_category_description', sa.Text(), nullable=True),
    sa.Column('bot9_instruction_category_slug', sa.String(length=256), nullable=True),
    sa.Column('bot9_instruction_category_icon', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bot9_chatbot_id'], ['chatbots.bot9_chatbot_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('bot9_chatbot_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bot9_chatbot_id'], ['chatbots.bot9_chatbot_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chats_bot9_chatbot_id'), ['bot9_chatbot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chats_user_id'), ['user_id'], unique=False)

    op.create_table('action_curls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('action_name', sa.String(length=256), nullable=False),
    sa.Column('curl_as_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chatbot_instructions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bot9_chatbot_id', sa.UUID(), nullable=False),
    sa.Column('bot9_instruction_id', sa.UUID(), nullable=False),
    sa.Column('bot9_instruction_name', sa.String(length=256), nullable=False),
    sa.Column('bot9_instruction_text', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bot9_chatbot_id'], ['chatbots.bot9_chatbot_id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['chatbot_instruction_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', name='role_enum'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tool_name', sa.String(length=256), nullable=True),
    sa.Column('tool_use_id', sa.String(length=256), nullable=True),
    sa.Column('tool_input', sa.JSON(), nullable=True),
    sa.Column('tool_result', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('chatbot_instructions')
    op.drop_table('action_curls')
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chats_user_id'))
        batch_op.drop_index(batch_op.f('ix_chats_bot9_chatbot_id'))

    op.drop_table('chats')
    op.drop_table('chatbot_instruction_categories')
    op.drop_table('chatbot_actions')
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_tokens_bot9_token'))

    op.drop_table('tokens')
    with op.batch_alter_table('chatbots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chatbots_bot9_chatbot_id'))

    op.drop_table('chatbots')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    # ### end Alembic commands ###
